server:
  port: 8080
spring:
  application:
    name: "AutenticacionMS"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    usuarios: "/api/v1/usuarios"
    usuarioById: "/api/v1/usuarios/{id}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "autenticacion_db"
    schema: "public"
    username: "postgres"
    password: "admin"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
